### ISSUE TITLE
Panics when ENS name is unregistered 

### ISSUE THREAD

**Issue by iankressin** [iankressin/eql#13]
### Description
Queries to unregistered ENS names panics with unhandled error "Invalid address".

### Steps to reproduce
`GET balance FROM account iankguimaraes.eth ON eth`

**Comment by rizdarmwn** [comment]
Should we just create an error enum and returns the error to the front? Or do you already have any idea how to do it?

**Comment by iankressin** [comment]
@rizdarmwn we actually already have an enum for errors associated with ENS. The problem is that we're panicking which doesn't allow the error to propagate correctly
https://github.com/iankressin/eql/blob/7d1920dcd314a2114a3ff87ca95e53acef489402/crates/core/src/interpreter/backend/execution_engine.rs#L101

To fix this bug, we should remove the panic and handle the exception in a way it can be propagated upstream

**Comment by rizdarmwn** [comment]
@iankressin I see, I will check & do this then.
