### ISSUE TITLE
Add symbol to fetch all fields

### ISSUE THREAD

**Issue by DistributedDoge** [iankressin/eql#17]
To save typing, language could include SQL-like `*` wildcard to get all fields we cannot be bothered to enumerate.

`GET * FROM block 1 ON eth`

I think new grammar could new like this:
```
fields    = { "*" | account_field_list | block_field_list | tx_field_list }

// For each field type:
account_field_list = _{ account_field ~ (", " ~ account_field)* }
```

I feel I should be able to handle Rust part of implementing that, which would be to modify [frontend/parser](https://github.com/iankressin/eql/blob/3acbcb3152024deebf2e163e788d9ae38d223376/crates/core/src/interpreter/frontend/parser.rs#L30) and create `expand_wildcard(entity: &str)` helper function. Does it make sense?

**Comment by iankressin** [comment]
> I think new grammar could new like this:

That's it. 

> Does it make sense?

Yes sir. We can either pass all the fields to interpret's backend or create a new enum variant called `All` [here](https://github.com/iankressin/eql/blob/3acbcb3152024deebf2e163e788d9ae38d223376/crates/core/src/common/types.rs#L32).

Let me know if you need any help with it.

Thanks for handling this!
