### ISSUE TITLE
Improve EQL expression error readbility

### ISSUE THREAD

**Issue by yulesa** [iankressin/eql#27]
**Describe the bug**
When running EQL locally using a `.eql` file, errors are printed in a debug mode, being hard to understand.

**To Reproduce**
1. Run a locally a `.eql` file with an incorrect EQL expression.

**Expected behavior**
A formatted error like in the REPL format.

**Screenshots**
Current: top bash run. Expected: bottom bash run.
![image](https://github.com/user-attachments/assets/4e108b7f-547d-4541-acc2-c9ee6fac64ff)

**Comment by iankressin** [comment]
Fixed on https://github.com/iankressin/eql/pull/28
