### ISSUE TITLE
Bad address checksum in log filters

### ISSUE THREAD

**Issue by iankressin** [iankressin/eql#53]
**Describe the bug**
The `WHERE` clause for Logs requires the address to be in the checksum format. The same doesn't happen in other queries that uses the account addresses, such as Account queries

**To Reproduce**
https://eql.sh/?query=GET+*+FROM+log+WHERE+block+%3D+latest%2C+event_signature+%3D+Transfer%28address%2Caddress%2Cuint256%29%2C+address+%3D+0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48+ON+eth

**Expected behavior**
To allow non-checksum formatted values in the WHERE clause for logs

**Comment by ScovottoDavide** [comment]
Hello @iankressin. Can I work on this? 

If yes would you recommend always encoding the address into a checksummed format (even if it’s already valid) to avoid the possibility of encountering AddressError::InvalidChecksum?

**Comment by iankressin** [comment]
Hey @ScovottoDavide! Sure!

Yeah, the source of the problem what that exact scenario, a valid addresses are being rejected in log filters because they're not checksummed.

I believe it's enough if you simply parse the value of the filter to the checksum format.
